### ISSUE TITLE
Can you help with the value of style and content weights?

### ISSUE THREAD

**Issue by KushajveerSingh** [limingcv/Photorealistic-Style-Transfer#4]
I implemented your paper. I was able to produce matching results as your paper for most of the figures, but I have been struggling for this Amber image in `more_results/Amber`. Can you tell the style and content weights that you used for this image?

Also, seeing that it takes a lot of trials to get good results. Do you have any strategy for deciding on the values of the content and style weights.

**Comment by limingcv** [comment]
Sorry, I can't tell you the weight. Due to the limitation of computing resources, I did the results of these experiments in the Internet cafe. I didn't save these models, but saved the final results.

For this Amber image, I remember that I also spent a lot of time adjusting the weights to get the effect of the picture. You can try some different weights.

When the style image and content image have the same size, you should let the value of the style weight be about 10 times the weight of the content, otherwise，1 for style weight and 150 for content is a good initial value.

In addition, could you give a star to my project? It is very important to me, Thanks ♪(・ω・)ノ

**Comment by KushajveerSingh** [comment]
Didn't you say the opposite. 150 for content weight and 1 for style weight.

I wrote a blog post on your paper also. [link](https://medium.com/@kushajreal/all-you-need-for-photorealistic-style-transfer-in-pytorch-acb099667fc8)

Oh sorry, I forgot about the star.

**Comment by KushajveerSingh** [comment]
There is an UpSample class in the utils.py. You did not use this upsample class in your implementation. So did you try it and it did not give good results?

**Comment by limingcv** [comment]
Their effect is similar, but for efficiency reasons, I used nn.Upsample

**Comment by KushajveerSingh** [comment]
And for the content weight and style weight in your first reply. Didn't you say the opposite content_weight=150 and style_weight=1.

**Comment by limingcv** [comment]
yes, the content weight is 150, and style weight is 1

**Comment by KushajveerSingh** [comment]
Thanks
